name = "lcr-games"
pages_build_output_dir = ".open-next/assets"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
# Variáveis de ambiente devem ser configuradas no painel da Cloudflare (Secrets)
